version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    networks:
      keycloak: {}
      nginx-main: {}
      oauth2-proxy: {}
    depends_on:
      - nginx-main

  nginx-main:
    container_name: nginx-main
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx-main.conf:/etc/nginx/conf.d/default.conf
      - ./landing.html:/usr/share/nginx/html/landing.html
    networks:
      hello-server: {}
      hi-server: {}
      oauth2-proxy: {}
      nginx-main: 
        aliases:
          - landing.localtest.me
    depends_on:
      - keycloak
      - hello-server
      - hi-server

  hello-server:
    container_name: hello-server-8080
    image: jyyoon0615/hello-world:8080
    expose:
      - 8080
    networks:
      hello-server:
        aliases:
          - hello-server.localtest.me

  hi-server:
    container_name: hi-server-8080
    image: jyyoon0615/hi-world:8080
    expose:
      - 8080
    networks:
      hi-server:
        aliases:
          - hi-server.localtest.me

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0
    hostname: keycloak
    command:
      - 'start-dev'
      - '--http-port=9080'
      - '--import-realm'
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 9080:9080/tcp
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:13.9
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      keycloak: {}

networks:
  keycloak: {}
  nginx-main: {}
  hello-server: {}
  hi-server: {}
  oauth2-proxy: {}