version: '3.0'
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    networks:
      keycloak: {}
      nginx-main: {}
      oauth2-proxy: {}
      keycloak-test-network: {}
    depends_on:
      - keycloak

  nginx-main:
    container_name: nginx-main
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx-main.conf:/etc/nginx/conf.d/default.conf
      - ./landing.html:/usr/share/nginx/html/landing.html
      - ./permission_denied.html:/usr/share/nginx/html/permission_denied.html
    networks:
      oauth2-proxy: {}
      nginx-main: 
        aliases:
          - landing.localtest.me
      keycloak-test-network: {}
    depends_on:
      - oauth2-proxy
  
  nginx-authentication:
    container_name: nginx-authentication
    image: nginx:1.21.5-alpine
    ports:
      - 81:80
    volumes:
      - ./nginx-authentication.conf:/etc/nginx/conf.d/default.conf
      - ./permission_denied.html:/usr/share/nginx/html/permission_denied.html
    networks:
      hello-server: {}
      hi-server: {}
      authentication-server: {}
      oauth2-proxy: {}
      keycloak-test-network: {}
    depends_on:
      - oauth2-proxy

  hello-server:
    container_name: hello-server-8080
    image: jyyoon0615/hello-world:8080
    expose:
      - 8080
    networks:
      hello-server:
        aliases:
          - hello-server.localtest.me
      keycloak-test-network: {}

  hi-server:
    container_name: hi-server-8080
    image: jyyoon0615/hi-world:8080
    expose:
      - 8080
    networks:
      hi-server:
        aliases:
          - hi-server.localtest.me
      keycloak-test-network: {}

  authentication-server:
    container_name: authentication-server-8080
    image: jyyoon0615/authentication-server:8080
    ports:
      - 8080:8080
    environment:
      OAUTH2_PROXY_URL: http://oauth2-proxy:4180/oauth2/userinfo
      ID_ALLOWED_ALL: 5f5cbf35-8f39-422f-9b36-d5b94dcd6733
      ID_ALLOWED_HI: 0fa64399-8d11-4d00-9d22-67452f9edede
      ID_ALLOWED_NONE: 65a0e380-197b-4ca3-9940-c777f6c40b4c
      COOKIE_NAME: _oauth2_proxy
    networks:
      authentication-server:
        aliases:
          - authentication-server.localtest.me
      keycloak-test-network: {}
      oauth2-proxy: {}

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0
    hostname: keycloak
    command:
      - 'start-dev'
      - '--http-port=9080'
      - '--import-realm'
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 9080:9080/tcp
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
      keycloak-test-network: {}
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:13.9
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      # keycloak: {}
      keycloak-test-network: {}

networks:
  keycloak: {}
  nginx-main: {}
  hello-server: {}
  hi-server: {}
  oauth2-proxy: {}
  authentication-server: {}
  keycloak-test-network: {}